apiVersion: v1
kind: Pod
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  containers:
    - name: nodeapp
      image: nagasatishdocker/nodeapp-docker-k8s:tagVersion
      ports:
        - containerPort: 8080
